version: '3.8'
# This is run on coolify under a seperate service so we don't restart it on
# every git push!
services:
  pgbouncer:
    image: edoburu/pgbouncer:v1.24.0-p1
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-6382}
      - DB_NAME=${DB_NAME:-postgres}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=5
      - AUTH_TYPE=scram-sha-256
      - ADMIN_USERS=${DB_USER:-postgres}
    ports:
      - "6432:6432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5 